apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-csv-write-job
  namespace: spark
spec:
  volumes: 
    - name: files 
      persistentVolumeClaim:
        claimName: pvc
  sparkConf:
    spark.jars.packages: "org.apache.spark:spark-avro_2.12:3.5.0"
    spark.driver.extraJavaOptions: "-Dtemp.cache.dir=/tmp -Dtemp.home=/tmp"
    spark.kubernetes.allocation.batch.size: "5"
  type: Python
  sparkVersion: "3.5.0"
  mode: cluster
  image: spark-py:0.0.1 
  mainApplicationFile: /pyspark.py 
  driver:
    cores: 4
    coreLimit: "1200m"
    memory: "2g"
    labels:
      version: 3.5.0
    volumeMounts:
      - name: files 
        mountPath: /
  executor:
    cores: 4
    instances: 1
    memory: "2g"
    labels:
      version: 3.5.0
    volumeMounts:
      - name: files 
        mountPath: /
---

# Notes
# Service Account: to identify the process running inside the spark (job). to scope permissions. for minikube it is overkill
# TODO: Use pyspark.submit() method to do the population in master node ig 
